### ISSUE TITLE
IndexError: index 109 is out of bounds for dimension 1 with size 1

### ISSUE THREAD

**Issue by zheng-xiao** [JiaRenChang/RealtimeStereo#14]
Hi, 
I meet an issues:
Traceback (most recent call last):
  File "finetune.py", line 205, in <module>
    main()
  File "finetune.py", line 179, in main
    test_loss = test(imgL,imgR, disp_L)
  File "finetune.py", line 140, in test
    true_disp[index[0][:], index[1][:], index[2][:]]-pred_disp[index[0][:], index[1][:], index[2][:]])
IndexError: index 109 is out of bounds for dimension 1 with size 1

I don't know the reason. Could you help me?

**Comment by JiaRenChang** [comment]
Hi, @zheng-xiao,
   You can check the size of both images (ture_disp and pred_disp).
   It should be in 3 dimension.
Jia-Ren

**Comment by zheng-xiao** [comment]
Thanks. I solve it.



---- 回复的原邮件 ----
| 发件人 | Jia-Ren ***@***.***> |
| 日期 | 2022年05月11日 20:07 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [JiaRenChang/RealtimeStereo] IndexError: index 109 is out of bounds for dimension 1 with size 1 (Issue #14) |

Hi, @zheng-xiao,
You can check the size of both images (ture_disp and pred_disp).
It should be in 3 dimension.
Jia-Ren
